### ISSUE TITLE
MSBuild Task how to support netcore3.1 or net5.0？

### ISSUE THREAD

**Issue by wuweilaiya** [holajan/DC.Build.Tasks#1]
MSBuild Task how to support netcore3.1 or net5.0？
use netcore3.1 have a error：Lack of dependence dll
[DC.Build.Tasks-master.zip](https://github.com/holajan/DC.Build.Tasks/files/6565558/DC.Build.Tasks-master.zip)

![image](https://user-images.githubusercontent.com/30889371/120089373-1762ba00-c12c-11eb-8c74-1881b780f8c0.png)

**Comment by holajan** [comment]
Just use DC.Build.Tasks.dll from dist directory, it works for all projects (netcore3.1 or net5.0).
